#7.29
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/test
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver

#spring:
#  mail:
#    host: smtp.qq.com
#    username: 2983606672@qq.com
#    password: kjmessrxvjlgdebg
#    port: 465
#    protocol: smtp


#spring:
#  profiles:
#    active:
#    active: '@environment@'
##spring.application.name=baima-Springboot
#
##server.port=8080
##test.hello=YYDS
#
#

#7.31

server:
  port: 8081
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
jpa:
  show-sql: true
  hibernate:
    ddl-auto: update



##mvc:
##  static-path-pattern: /static/**
#security:
#  user:
#    name: 'admin'
#    password: '123456'
#    roles:
#      - admin
#      - user



